# Generated by Django 3.0.4 on 2020-03-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(max_length=30)),
                ('from_place', models.CharField(max_length=30)),
                ('to_place', models.CharField(max_length=30)),
                ('depart_at_from', models.TimeField()),
                ('arrival_at_to', models.TimeField()),
                ('seat_no', models.IntegerField()),
                ('available', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('off', models.IntegerField(default=0)),
                ('collected', models.IntegerField(default=0)),
            ],
        ),
    ]
