# Generated by Django 3.0.4 on 2020-04-04 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelling',
            name='collected',
        ),
        migrations.RemoveField(
            model_name='travelling',
            name='off',
        ),
        migrations.AddField(
            model_name='travelling',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
