# Generated by Django 3.0.4 on 2020-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20200404_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelling',
            old_name='arrival_at_to',
            new_name='Arrival_at_to',
        ),
        migrations.RenameField(
            model_name='travelling',
            old_name='available',
            new_name='Available',
        ),
        migrations.RenameField(
            model_name='travelling',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='travelling',
            old_name='depart_at_from',
            new_name='Depart_at_from',
        ),
        migrations.RenameField(
            model_name='travelling',
            old_name='flight',
            new_name='Flight',
        ),
        migrations.RenameField(
            model_name='travelling',
            old_name='from_place',
            new_name='From_place',
        ),
        migrations.RenameField(
            model_name='travelling',
            old_name='rate',
            new_name='Rate',
        ),
        migrations.RenameField(
            model_name='travelling',
            old_name='seat_no',
            new_name='Seat_no',
        ),
        migrations.RenameField(
            model_name='travelling',
            old_name='to_place',
            new_name='To_place',
        ),
        migrations.AddField(
            model_name='travelling',
            name='Travel_class',
            field=models.CharField(choices=[('Economy', 'Economy'), ('First_class', 'First_class'), ('Business', 'Business')], default='eco', max_length=12),
        ),
    ]
