# Generated by Django 3.0.4 on 2020-11-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_auto_20200404_2152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Travelling',
            new_name='Flight',
        ),
    ]
