# Generated by Django 3.0.4 on 2020-11-15 18:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flight', '0005_auto_20201115_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('airline_name', models.CharField(max_length=50)),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
