# Generated by Django 3.0.4 on 2020-11-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
